# Generated by Django 5.1.4 on 2025-01-03 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='street_address',
            new_name='address',
        ),
    ]
