# Generated by Django 5.1.4 on 2025-01-03 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_rename_street_address_checkout_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='pin_code',
            new_name='pincode',
        ),
    ]
